'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const commons=require('../commons');
const planning=require('../production-planning');

function page(overrides={}){return{pageid:12,title:'File:Ganesh idol.jpg',imageinfo:[{url:'https://upload.wikimedia.org/wikipedia/commons/a/a1/Ganesh_idol.jpg',descriptionurl:'https://commons.wikimedia.org/wiki/File:Ganesh_idol.jpg',mime:'image/jpeg',width:1600,height:1200,size:300000,extmetadata:{Artist:{value:'Creator Example'},LicenseShortName:{value:'CC BY-SA 4.0'},LicenseUrl:{value:'https://creativecommons.org/licenses/by-sa/4.0/'},...overrides}}]};}

test('Commons API query uses a plain topic, origin=* and actual imageinfo fields',()=>{const url=commons.buildSearchUrl('Ganesh Chaturthi Mumbai');assert.equal(url.searchParams.get('origin'),'*');assert.equal(url.searchParams.get('gsrsearch'),'Ganesh Chaturthi Mumbai');assert.equal(url.searchParams.get('iiurlwidth'),'1600');assert.match(url.searchParams.get('iiprop'),/mime/);assert.doesNotMatch(url.searchParams.get('gsrsearch'),/filetype:/i);});
test('classifies real supported image and video MIME values',()=>{for(const mime of ['image/jpeg','image/png','image/webp','image/tiff'])assert.equal(commons.classifyMime(mime),'photo');for(const mime of ['video/mp4','video/webm','video/ogg'])assert.equal(commons.classifyMime(mime),'video');assert.equal(commons.classifyMime('application/pdf'),null);});
test('extracts Wikimedia creator, licence evidence, licence URL and actual page URL',()=>{const asset=commons.normalizedPage(page());assert.equal(asset.creator,'Creator Example');assert.equal(asset.license,'CC BY-SA 4.0');assert.equal(asset.licenseUrl,'https://creativecommons.org/licenses/by-sa/4.0/');assert.equal(asset.pageUrl,'https://commons.wikimedia.org/wiki/File:Ganesh_idol.jpg');assert.equal(asset.mediaUrl,'https://upload.wikimedia.org/wikipedia/commons/a/a1/Ganesh_idol.jpg');assert.equal(asset.mediaType,'photo');assert.equal(asset.metadataComplete,true);});
test('supports alternate creator and licence metadata labels without inventing values',()=>{const item=page({Artist:undefined,Credit:{value:'Archive'},LicenseShortName:undefined,UsageTerms:{value:'Public domain'}});const asset=commons.normalizedPage(item);assert.equal(asset.creator,'Archive');assert.equal(asset.license,'Public domain');assert.equal(asset.metadataComplete,true);});
test('records Copyrighted=false without fabricating the required licence URL',()=>{const item=page({LicenseShortName:undefined,UsageTerms:undefined,LicenseUrl:undefined,Copyrighted:{value:'false'}});const asset=commons.normalizedPage(item);assert.equal(asset.license,'Public domain');assert.equal(asset.licenseEvidence,'Copyrighted: false');assert.equal(asset.metadataComplete,false);assert.equal(asset.rightsStatus,'UNVERIFIED');});
test('rejects missing rights evidence and never invents file page or creator',()=>{const asset=commons.normalizedPage({pageid:1,title:'File:x.jpg',imageinfo:[{url:'https://upload.wikimedia.org/x.jpg',mime:'image/jpeg',width:1000,height:1000,size:10,extmetadata:{}}]});assert.equal(asset.creator,'');assert.equal(asset.pageUrl,'');assert.equal(asset.metadataComplete,false);assert.match(asset.rejectReasons.join(' '),/creator metadata missing/);assert.match(asset.rejectReasons.join(' '),/license metadata missing/);});
test('classifies media from actual MIME even when caller concept says nothing about type',()=>{const item=page();item.imageinfo[0].mime='video/mp4';item.imageinfo[0].url='https://upload.wikimedia.org/a/video.mp4';assert.equal(commons.normalizedPage(item).mediaType,'video');});
test('keeps unverified research candidates visible while separating production-verified results',()=>{const parsed=commons.parseSearchResponse({query:{pages:[page(),page({Artist:undefined})]}});assert.equal(parsed.diagnostics.raw,2);assert.equal(parsed.diagnostics.rightsComplete,1);assert.equal(parsed.results.length,2);assert.equal(parsed.verifiedResults.length,1);assert.equal(parsed.diagnostics.rejected,1);assert.equal(parsed.results[1].metadataComplete,false);});
test('Commons retry succeeds after a transient network failure',async()=>{let calls=0;const result=await commons.searchCommons('Ganpati',{attempts:2,sleep:async()=>{},fetchImpl:async()=>{calls++;if(calls===1)throw new Error('temporary offline');return{ok:true,status:200,text:async()=>JSON.stringify({query:{pages:[page()]}})};}});assert.equal(calls,2);assert.equal(result.results.length,1);});
test('failed Commons retries report the actual failure and attempt count',async()=>{await assert.rejects(commons.searchCommons('temple',{attempts:2,sleep:async()=>{},fetchImpl:async()=>{throw new Error('network down');}}),/failed after 2 attempts: network down/);});
test('Commons non-JSON rate-limit body reports a safe status without parser internals',async()=>{await assert.rejects(commons.searchCommons('Mumbai',{attempts:1,fetchImpl:async()=>({ok:false,status:429,text:async()=>'<html>too many requests</html>'})}),/non-JSON response \(HTTP 429\)/);});
test('production requires an actual reusable licence URL even if other licence text exists',()=>{const asset={...commons.normalizedPage(page({LicenseUrl:undefined})),description:'Ganesh idol India temple',title:'Ganesh idol India temple',width:1600,height:1200,licenseUrl:''};assert.equal(asset.metadataComplete,false);assert.equal(planning.rankAsset(asset,{terms:['ganesh','idol'],mediaPreference:'EITHER'}),-Infinity);});
test('duplicate remote media identity ignores query strings and thumbnail variations',()=>{const asset={...commons.normalizedPage(page()),description:'Ganesh idol India',title:'Ganesh idol India',width:1600,height:1200};const duplicate={...asset,id:'another-record',mediaUrl:`${asset.mediaUrl}?width=1600`,pageUrl:`${asset.pageUrl}?oldformat=true`};const used=new Set(planning.assetIdentityKeys(asset));assert.equal(planning.rankAsset(duplicate,{terms:['ganesh','idol'],usedIds:used}),-Infinity);});
test('32 scene slots require 32 distinct verified media identities',()=>{const assets=Array.from({length:32},(_,index)=>({id:`commons-${index}`,filename:`commons-${index}.jpg`,mediaUrl:`https://upload.wikimedia.org/${index}.jpg`,pageUrl:`https://commons.wikimedia.org/wiki/File:${index}.jpg`,hash:`sha256-${index}`,metadataComplete:true,creator:'Creator',license:'CC BY',width:1400,height:1000}));assert.equal(new Set(assets.map(asset=>asset.id)).size,32);assert.equal(new Set(assets.map(asset=>asset.mediaUrl)).size,32);for(let reel=0;reel<4;reel++)assert.equal(new Set(assets.slice(reel*8,reel*8+8).map(asset=>asset.id)).size,8);});
test('Vercel same-origin browser asset routes exist and do not route through localhost',()=>{const fs=require('node:fs');assert.equal(fs.existsSync(require.resolve('../api/commons-search')),true);assert.equal(fs.existsSync(require.resolve('../api/commons-media')),true);const source=fs.readFileSync(require.resolve('../asset-import'),'utf8');assert.match(source,/\/api\/commons-media\?url=/);assert.doesNotMatch(source,/127\.0\.0\.1:8766/);});
test('Vercel Commons search route returns real parsed results and diagnostics',async()=>{const handler=require('../api/commons-search');const original=global.fetch;global.fetch=async()=>({ok:true,status:200,text:async()=>JSON.stringify({query:{pages:[page()]}})});const result={statusCode:0,headers:{},status(value){this.statusCode=value;return this;},json(value){this.body=value;return this;}};try{await handler({method:'GET',query:{q:'Ganesh Chaturthi'}},result);assert.equal(result.statusCode,200);assert.equal(result.body.results[0].pageUrl,'https://commons.wikimedia.org/wiki/File:Ganesh_idol.jpg');assert.equal(result.body.diagnostics.rightsComplete,1);}finally{global.fetch=original;}});
test('Vercel media proxy streams returned bytes and refuses unrelated hosts',async()=>{const handler=require('../api/commons-media');const original=global.fetch;global.fetch=async()=>new Response(Buffer.from('actual-source-bytes'),{status:200,headers:{'Content-Type':'image/jpeg'}});const chunks=[];const result={headers:{},setHeader(name,value){this.headers[name]=value;},write(chunk){chunks.push(Buffer.from(chunk));return true;},end(chunk){if(chunk)chunks.push(Buffer.from(chunk));this.ended=true;},status(value){this.statusCode=value;return this;},json(value){this.body=value;return this;}};try{await handler({method:'GET',query:{url:'https://upload.wikimedia.org/wikipedia/commons/test.jpg'}},result);assert.equal(result.statusCode,200);assert.equal(Buffer.concat(chunks).toString(),'actual-source-bytes');assert.equal(result.headers['Content-Type'],'image/jpeg');const denied={status(value){this.statusCode=value;return this;},json(value){this.body=value;return this;}};await handler({method:'GET',query:{url:'https://example.com/file.jpg'}},denied);assert.equal(denied.statusCode,400);}finally{global.fetch=original;}});
test('global Hungarian assignment fills 32 scenes from 50 licensed photos with zero videos',()=>{const pillars=['The Moment','The Detail','The Energy','The Meaning'];const scenes=pillars.flatMap(pillar=>Array.from({length:8},(_,index)=>({id:`${pillar}-${index}`,pillar,topic:'Mumbai',description:`${pillar} scene ${index} city atmosphere`,shotType:index%2?'close-up':'wide establishing',mediaPreference:index%2?'VIDEO PREFERRED':'EITHER'})));const candidates=Array.from({length:50},(_,index)=>({id:`commons-${index}`,commonsPageId:String(index),title:`Mumbai city photo ${index}`,description:'Mumbai local culture',discoveryQueries:['Mumbai','Mumbai people','Mumbai city'],mediaType:'photo',mime:'image/jpeg',width:1400,height:950,metadataComplete:true,creator:`Creator ${index}`,license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',pageUrl:`https://commons.wikimedia.org/wiki/File:Mumbai_${index}.jpg`,mediaUrl:`https://upload.wikimedia.org/wikipedia/commons/Mumbai_${index}.jpg`}));const assigned=planning.assignAssetsToScenes(scenes,candidates,{topic:'Mumbai'});assert.equal(assigned.length,32);assert.ok(assigned.every(row=>row.asset&&row.score>0));assert.equal(new Set(assigned.map(row=>row.asset.commonsPageId)).size,32);assert.ok(assigned.every(row=>row.asset.mediaType==='photo'));});
test('global assignment has no exact scene keyword gate and rejects assets without rights',()=>{const scenes=[{id:'wide-city',topic:'Mumbai',description:'opening city atmosphere',shotType:'wide establishing',mediaPreference:'VIDEO PREFERRED'}];const relevant={id:'mumbai-1',commonsPageId:'mumbai-1',title:'Mumbai at dusk',discoveryQueries:['Mumbai city'],mediaType:'photo',width:1280,height:720,metadataComplete:true,creator:'Photographer',license:'CC BY',licenseUrl:'https://creativecommons.org/licenses/by/4.0/',pageUrl:'https://commons.wikimedia.org/wiki/File:Mumbai.jpg',mediaUrl:'https://upload.wikimedia.org/Mumbai.jpg'};const denied={...relevant,id:'unsafe',commonsPageId:'unsafe',licenseUrl:'',pageUrl:'https://commons.wikimedia.org/wiki/File:Unsafe.jpg',mediaUrl:'https://upload.wikimedia.org/Unsafe.jpg'};const result=planning.assignAssetsToScenes(scenes,[relevant,denied],{topic:'Mumbai'});assert.equal(result[0].asset.id,'mumbai-1');assert.equal(planning.assignAssetsToScenes(scenes,[denied],{topic:'Mumbai'})[0].asset,null);});
test('global assignment treats intersecting media URLs as one asset even when ids differ',()=>{const scene={topic:'Mumbai',description:'opening city atmosphere',mediaPreference:'EITHER'};const base={title:'Mumbai city',mediaType:'photo',width:1280,height:720,metadataComplete:true,creator:'Creator',license:'CC BY',licenseUrl:'https://creativecommons.org/licenses/by/4.0/'};const first={...base,id:'record-a',commonsPageId:'file-a',pageUrl:'https://commons.wikimedia.org/wiki/File:A.jpg',mediaUrl:'https://upload.wikimedia.org/A.jpg'};const duplicate={...base,id:'record-b',commonsPageId:'file-b',pageUrl:'https://commons.wikimedia.org/wiki/File:B.jpg',mediaUrl:'https://upload.wikimedia.org/A.jpg?width=1280'};const other={...base,id:'record-c',commonsPageId:'file-c',pageUrl:'https://commons.wikimedia.org/wiki/File:C.jpg',mediaUrl:'https://upload.wikimedia.org/C.jpg'};const result=planning.assignAssetsToScenes([scene,{...scene,id:'second'}],[first,duplicate,other],{topic:'Mumbai'});assert.equal(result.filter(row=>row.asset).length,2);assert.equal(new Set(result.map(row=>planning.assetIdentityKeys(row.asset).find(key=>key.startsWith('media:')))).size,2);});
test('browser importer verifies decode, dimensions, MIME, licence and stores actual downloaded Blob',()=>{const source=require('node:fs').readFileSync(require.resolve('../asset-import'),'utf8');assert.match(source,/createImageBitmap|naturalWidth|videoWidth/);assert.match(source,/indexedDB/);assert.match(source,/createObjectURL\(blob\)/);assert.match(source,/metadataComplete:true/);assert.match(source,/blob\.size/);});
test('render QC still requires final portrait dimensions, H.264 and decode validation',()=>{const source=require('node:fs').readFileSync(require.resolve('../app'),'utf8');for(const rule of ['resolution:preview.videoWidth===1080&&preview.videoHeight===1920','h264:blob.type.startsWith(\'video/mp4\')','decodeTest','musicFree:stream.getAudioTracks().length===0','rightsMetadata'])assert.ok(source.includes(rule),`Missing QC rule ${rule}`);});
test('local worker keeps its disk-backed job and media import boundary',()=>{const source=require('node:fs').readFileSync(require.resolve('../server'),'utf8');assert.match(source,/\/api\/assets\/import/);assert.match(source,/\/api\/worker\/jobs/);assert.match(source,/ASSET_DIR/);});