'use strict';
(function(root){
  const DB='fob-real-assets',STORE='media',MAX=100*1024*1024;
  function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async function save(id,blob){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id,blob,savedAt:Date.now()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
  async function get(id){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).get(id);request.onsuccess=()=>resolve(request.result?.blob||null);request.onerror=()=>reject(request.error);});}
  async function digest(blob){if(!crypto?.subtle)return'';const hash=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return[...new Uint8Array(hash)].map(value=>value.toString(16).padStart(2,'0')).join('');}
  function dimensions(blob,type){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob);if(type==='video'){const video=document.createElement('video');video.preload='metadata';video.muted=true;video.onloadedmetadata=()=>{URL.revokeObjectURL(url);video.removeAttribute('src');resolve({width:video.videoWidth,height:video.videoHeight,durationSeconds:video.duration});};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Downloaded video could not be decoded by the browser.'));};video.src=url;}else{const image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve({width:image.naturalWidth,height:image.naturalHeight});};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Downloaded image is empty or could not be decoded.'));};image.src=url;}});}
  async function fetchBlob(asset){const proxy=`/api/commons-media?url=${encodeURIComponent(asset.mediaUrl)}`;let firstError=null;const hosted=!(location.hostname==='127.0.0.1'||location.hostname==='localhost');const attempts=hosted?[proxy,asset.mediaUrl]:[asset.mediaUrl,proxy];for(const target of attempts){try{const response=await fetch(target,{mode:target===asset.mediaUrl?'cors':'same-origin',credentials:'omit'});if(!response.ok){let info={};try{info=await response.json();}catch{}throw new Error(info.error||`Media request returned HTTP ${response.status}.`);}const blob=await response.blob();if(!blob.size)throw new Error('Media response was empty.');return blob;}catch(error){firstError=firstError||error;}}throw new Error(`Wikimedia media download failed: ${firstError?.message||'unknown error'}.`);}
  async function restore(asset){const key=asset?.browserAssetKey||asset?.browserMasterKey;if(!key)return asset;const blob=await get(key);if(!blob)return{...asset,localUrl:'',renderUrl:'',browserStorageMissing:true};const localUrl=URL.createObjectURL(blob);if(asset.browserMasterKey)return{...asset,renderUrl:localUrl};const decoded=await dimensions(blob,asset.mediaType);return{...asset,localUrl,width:decoded.width,height:decoded.height,size:blob.size};}
  async function saveMaster(id,blob){const key=`render-${id}`;await save(key,blob);return{key,url:URL.createObjectURL(blob)};}
  async function saveUserAsset(file,details={}){const id=`upload-${crypto.randomUUID()}`;await save(id,file);const pageUrl=`local-upload:${encodeURIComponent(file.name||'media')}`;return{...details,id,assetId:id,filename:file.name||`${id}.media`,browserAssetKey:id,storageMode:'browser-indexeddb',localUrl:URL.createObjectURL(file),size:file.size,source:'User Upload',sourceUrl:'User Upload',sourcePage:pageUrl,creator:'User-provided',license:'User confirms permission to use this media',licenseUrl:'',pageUrl,userRightsConfirmed:true,rightsStatus:'User confirmed',metadataComplete:true,downloadVerified:true,importedAt:new Date().toISOString()};}
  async function importAsset(asset){if(asset?.source!=='Wikimedia Commons'||!asset.creator||!asset.license||!asset.licenseUrl||!asset.licenseCompatible||!asset.pageUrl||!asset.mediaUrl||!asset.licenseEvidence)throw new Error('Asset source, actual file page, creator, licence and licence URL are required.');if(!/^https:\/\/(upload\.wikimedia\.org|commons\.wikimedia\.org)\//i.test(asset.mediaUrl)||!/^https:\/\/commons\.wikimedia\.org\/wiki\//i.test(asset.pageUrl))throw new Error('Asset URLs must be the actual HTTPS Wikimedia media and file-page URLs.');
    const blob=await fetchBlob(asset);if(!blob.size)throw new Error('Wikimedia returned an empty asset.');if(blob.size>MAX)throw new Error('Asset exceeds the 100 MB browser import limit.');const expected=String(asset.mime||'').toLowerCase(),actual=blob.type.toLowerCase();const expectedKind=expected.startsWith('image/')?'photo':expected.startsWith('video/')?'video':'';const actualKind=actual.startsWith('image/')?'photo':actual.startsWith('video/')?'video':'';if(expectedKind&&actualKind&&expectedKind!==actualKind)throw new Error(`Downloaded media type ${actual||'(unknown)'} does not match Commons media type ${expected||'(unknown)'}.`);const type=asset.mediaType;const decoded=await dimensions(blob,type);if(!(decoded.width>0&&decoded.height>0))throw new Error('Decoded media has invalid dimensions.');if(asset.width&&asset.height&&(decoded.width!==Number(asset.width)||decoded.height!==Number(asset.height)))throw new Error(`Decoded dimensions ${decoded.width}×${decoded.height} do not match Commons metadata ${asset.width}×${asset.height}.`);const id=`commons-${asset.id}`,hash=await digest(blob);await save(id,blob);return{...asset,id,assetId:id,filename:`${id}.${type==='video'?'mp4':'media'}`,browserAssetKey:id,storageMode:'browser-indexeddb',localUrl:URL.createObjectURL(blob),width:decoded.width,height:decoded.height,size:blob.size,hash,importedAt:new Date().toISOString(),metadataComplete:true,downloadVerified:true};}
  root.FOBAssetImport={importAsset,restore,saveMaster,saveUserAsset};
})(globalThis);