'use strict';
const {searchCommons}=require('../commons');
const {analyzeAssets}=require('../vision-provider');

function json(res,status,payload){res.setHeader('Cache-Control','no-store');return res.status(status).json(payload);}
function routeParts(req){const value=req.query?.path;if(Array.isArray(value))return value.map(String).filter(Boolean);if(value)return String(value).split('/').filter(Boolean);return String(req.url||'').split('?')[0].replace(/^\/api\/?/,'').split('/').filter(Boolean);}
async function bodyJson(req){if(req.body!==undefined&&req.body!==null){if(typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;return JSON.parse(Buffer.isBuffer(req.body)?req.body.toString('utf8'):String(req.body)||'{}');}const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>8*1024*1024)throw Object.assign(new Error('Request body is too large.'),{statusCode:413});chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');}
const instagramStatus=()=>({configured:false,connected:false,provider:'Instagram API',accountType:null,username:null,instagramUserId:null,expiresAt:null,scopes:[],message:'Hosted Vercel OAuth token persistence is disabled. Connect Instagram Insights from the local studio server; competitor research remains public-web only.'});
module.exports=async function handler(req,res){
 const parts=routeParts(req),method=String(req.method||'GET').toUpperCase();
 try{
  if(parts[0]==='assets'&&parts.length===1&&method==='GET'){const q=String(req.query?.q||new URL(req.url,'https://studio.invalid').searchParams.get('q')||'').trim();if(!q)return json(res,400,{error:'Enter a topic to search Wikimedia Commons.',results:[]});return json(res,200,{query:q,...await searchCommons(q)});}
  if(parts[0]==='assets'&&parts[1]==='import'&&method==='POST')return json(res,501,{ok:false,code:'BROWSER_IMPORT_REQUIRED',error:'Hosted import is not persisted on Vercel. The studio will download and verify this Commons asset directly in the browser.'});
  if(parts[0]==='assets'&&parts[1]==='upload'&&method==='POST')return json(res,501,{ok:false,code:'BROWSER_UPLOAD_REQUIRED',error:'Hosted file persistence is not enabled. The studio will keep this confirmed user file in browser IndexedDB.'});
  if(parts[0]==='renders'&&method==='POST')return json(res,501,{ok:false,code:'BROWSER_RENDER_STORAGE_REQUIRED',error:'Hosted MP4 persistence is not enabled. The studio will save the QC-passed master in browser IndexedDB.'});
  if(parts[0]==='vision'&&parts[1]==='analyze'&&method==='POST'){const payload=await bodyJson(req),apiKey=String(process.env.OPENAI_API_KEY||'').trim();if(!apiKey)return json(res,503,{ok:false,code:'VISION_NOT_CONFIGURED',error:'Set OPENAI_API_KEY to enable hosted visual analysis.'});const sourceAssets=Array.isArray(payload.assets)?payload.assets:[];if(!sourceAssets.length||sourceAssets.length>8)return json(res,400,{ok:false,error:'Analyze between one and eight assets per request.'});const assets=sourceAssets.map((asset,index)=>({assetId:String(asset.assetId||`asset-${index+1}`),label:String(asset.requirement||asset.filename||'').slice(0,500),mediaType:asset.mediaType==='video'?'video':'photo',mime:'image/jpeg',frames:(Array.isArray(asset.frameImages)?asset.frameImages:[]).slice(0,3).map(frame=>{const match=String(frame||'').match(/^data:([^;]+);base64,(.+)$/);if(!match)throw Object.assign(new Error('Vision frame payload must be a data URL.'),{statusCode:400});return Buffer.from(match[2],'base64');})}));if(assets.some(asset=>!asset.frames.length))return json(res,400,{ok:false,error:'Each asset needs at least one decoded analysis frame.'});const analyses=await analyzeAssets({assets,apiKey});return json(res,200,{ok:true,provider:'OpenAI Responses API',disclosure:'Hosted visual analysis used only the supplied frames. Results are evidence-based observations; uncertain scene matches remain for review.',analyses});}
  if(parts[0]==='instagram'){if(parts[1]==='status'&&method==='GET')return json(res,200,instagramStatus());if(parts[1]==='connect'&&method==='GET')return json(res,503,{ok:false,code:'INSTAGRAM_LOCAL_OAUTH_REQUIRED',error:'Instagram OAuth token persistence is local-only in this free deployment. Start the local studio to authorize your Creator/Business account.'});if(parts[1]==='callback'&&method==='GET')return json(res,503,{ok:false,code:'INSTAGRAM_LOCAL_OAUTH_REQUIRED',error:'Instagram OAuth callback is available only in the local studio where encrypted token storage is enabled.'});if(parts[1]==='sync'&&method==='POST')return json(res,503,{ok:false,code:'INSTAGRAM_LOCAL_OAUTH_REQUIRED',error:'Instagram Insights sync requires the local authorized connection.'});if(parts[1]==='insights'&&method==='GET')return json(res,404,{ok:false,error:'No hosted Instagram Insights cache is stored in Vercel.'});if(parts[1]==='disconnect'&&method==='POST')return json(res,200,{ok:true,connected:false});}
  return json(res,404,{ok:false,code:'API_ROUTE_NOT_FOUND',error:`Hosted API route not found: /api/${parts.join('/')}`});
 }catch(error){return json(res,Number(error.statusCode)||500,{ok:false,error:error.message||'Hosted API request failed.'});}
};